server:
  port: ${REAL_ESTATE_SERVER_PORT}

spring:
  application:
    name: real-estate

  datasource:
    url: jdbc:postgresql://${REAL_ESTATE_DB_HOST}:${HOST_REAL_ESTATE_DB_PORT}/${REAL_ESTATE_DB_NAME}
    username: ${REAL_ESTATE_USERNAME}
    password: ${REAL_ESTATE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 5MB

eureka:
  client:
    serviceUrl:
      defaultZone: ${TAPART_EUREKA_PROTOCOL}://${TAPART_EUREKA_INSTANCE_HOSTNAME}:${TAPART_SERVICE_REGISTRY_SERVER_PORT}/eureka/
  instance:
    prefer-ip-address: true

aws:
  s3:
    access-key: ${REAL_ESTATE_AWS_S3_ACCESS_KEY}
    secret-key: ${REAL_ESTATE_AWS_S3_SECRET_KEY}
    region: ${REAL_ESTATE_AWS_S3_REGION}
    endpoint: ${REAL_ESTATE_AWS_S3_ENDPOINT}
    bucket-name: ${REAL_ESTATE_AWS_S3_BUCKET_NAME}

kafka-bootstrap-servers: ${NOTIFICATION_KAFKA_BOOTSTRAP_SERVERS}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE