spring:
  application:
    name: service-registry
server:
  port: ${TAPART_SERVICE_REGISTRY_SERVER_PORT}

eureka:
  instance:
    hostname: ${TAPART_EUREKA_INSTANCE_HOSTNAME}
  client:
    fetch-registry: ${TAPART_EUREKA_CLIENT_FETCH_REGISTRY}
    register-with-eureka: ${TAPART_EUREKA_CLIENT_REGISTER_WITH_EUREKA}