server:
  port: ${API_GATEWAY_PORT}

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  application:
    name: api-gateway