server:
  port: ${API_GATEWAY_PORT}

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: ${TAPART_EUREKA_PROTOCOL}://${TAPART_EUREKA_INSTANCE_HOSTNAME}:${TAPART_SERVICE_REGISTRY_SERVER_PORT}/eureka/