server:
  port: ${EMAIL_NOTIFICATION_SERVER_PORT}

spring:
  application:
    name: email-notification
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  mail:
    host: ${EMAIL_NOTIFICATION_MAIL_HOST}
    port: ${EMAIL_NOTIFICATION_MAIL_PORT}
    username: ${EMAIL_NOTIFICATION_MAIL_USERNAME}
    password: ${EMAIL_NOTIFICATION_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${EMAIL_NOTIFICATION_MAIL_SMTP_AUTH}
          starttls:
            enable: ${EMAIL_NOTIFICATION_MAIL_SMTP_STARTTLS_ENABLE}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}