server:
  port: ${EMAIL_NOTIFICATION_SERVER_PORT}

spring:
  application:
    name: email-notification
  mail:
    host: ${EMAIL_NOTIFICATION_MAIL_HOST}
    port: ${EMAIL_NOTIFICATION_MAIL_PORT}
    username: ${EMAIL_NOTIFICATION_MAIL_USERNAME}
    password: ${EMAIL_NOTIFICATION_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${EMAIL_NOTIFICATION_MAIL_SMTP_AUTH}
          starttls:
            enable: ${EMAIL_NOTIFICATION_MAIL_SMTP_STARTTLS_ENABLE}

eureka:
  client:
    serviceUrl:
      defaultZone: ${TAPART_EUREKA_PROTOCOL}://${TAPART_EUREKA_INSTANCE_HOSTNAME}:${TAPART_SERVICE_REGISTRY_SERVER_PORT}/eureka/