server:
  port: ${USER_SERVER_PORT}

spring:
  application:
    name: auth

  datasource:
    url: jdbc:postgresql://${USER_DB_HOST}:${USER_DB_PORT}/${USER_DB_NAME}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

application:
  security:
    jwt:
      secret-key: ${SECURITY_JWT_SECRET_KEY}
      expiration: ${SECURITY_JWT_EXPIRATION}
      refresh-token:
        expiration: ${SECURITY_JWT_REFRESH_TOKEN_EXPIRATION}