server:
  port: 8080

spring:
  application:
    name: auth

  datasource:
    url: jdbc:postgresql://localhost:5434/user_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

kafka-bootstrap-servers: localhost:9092

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

application:
  security:
    jwt:
      secret-key: 7A5B713377684E693055426D673968734E2B573154424C646742734B6F755274
      expiration: 3600000 # one hour
      refresh-token:
        expiration: 604800000 # 7 days